apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: notiflex-healthcheck
  namespace: notiflex
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: notiflex-api
