apiVersion: v1
kind: Service
metadata:
  name: notiflex-api-preview
  namespace: notiflex
  labels:
    app: notiflex-api
spec:
  type: ClusterIP
  selector:
    app: notiflex-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
